spring.application.name=squad-manager-api
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:file:.env[.properties]
spring.docker.compose.enabled=${DOCKER_ENABLED:true}

# Fallback DataSource Configuration (Classic MySQL Server)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:squadmanager_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}